shared:
  shared: true

development:
  config:
    foo: true
    bar: false
    baz: 'something'
    pi:  <%= Math::PI %>

staging:

test:
  config:
    foo: false
    bar: true
    baz: 'something else'
    pi:  3.141
